import subprocess
import json
import os
from flask import Flask, jsonify
from dotenv import load_dotenv
from collections import defaultdict

load_dotenv()

app = Flask(_name_, static_folder='.')

GITHUB_USER   = os.getenv('GITHUB_USERNAME', 'mauryasagar')
GITHUB_REPO   = os.getenv('GITHUB_REPO', 'devs_first_mate')
SLACK_CHANNEL = os.getenv('SLACK_CHANNEL_ID', 'YOUR_CHANNEL_ID')


def run_coral(query):
    try:
        result = subprocess.run(
            ['coral', 'sql', '--output', 'json', query],
            capture_output=True, text=True, timeout=30
        )
        if result.returncode != 0:
            return None, result.stderr.strip()
        output = result.stdout.strip()
        if not output:
            return [], None
        rows = json.loads(output)
        return rows, None
    except FileNotFoundError:
        return None, "Coral CLI not found."
    except subprocess.TimeoutExpired:
        return None, "Coral query timed out."
    except json.JSONDecodeError:
        return [], None


def find_duplicates(issues):
    stop_words = {'the','and','for','are','but','not','you','all','can','had','her','was','one','our','out','day','get','has','him','his','how','its','may','new','now','old','see','two','who','did','let','put','say','she','too','use','add','bug','fix','feat','page','issue','error','problem'}
    keyword_map = defaultdict(list)
    for issue in issues:
        title = issue.get('title', '').lower()
        words = set(w for w in title.split() if len(w) > 3 and w not in stop_words)
        for word in words:
            keyword_map[word].append(issue)

    duplicates = []
    seen_pairs = set()
    for word, group in keyword_map.items():
        if len(group) > 1:
            for i in range(len(group)):
                for j in range(i + 1, len(group)):
                    a = group[i].get('number')
                    b = group[j].get('number')
                    pair = tuple(sorted([a, b]))
                    if pair not in seen_pairs:
                        seen_pairs.add(pair)
                        duplicates.append({
                            'issue_a': group[i],
                            'issue_b': group[j],
                            'matched_keyword': word
                        })
    return duplicates


def draft_release_notes(prs):
    if not prs:
        return None
    lines = ["## Release Notes\n", "### What's Changed\n"]
    for pr in prs:
        title = pr.get('title', 'Untitled')
        number = pr.get('number', '?')
        user = pr.get('user_login', 'unknown')
        lines.append(f"- {title} (#{number}) — @{user}")
    lines.append(f"\n**Full Changelog**: https://github.com/{GITHUB_USER}/{GITHUB_REPO}/commits/main")
    lines.append("\n_Auto-generated by Dev's First Mate · Powered by Coral_")
    return '\n'.join(lines)


@app.route('/')
def home():
    from flask import send_from_directory
    return send_from_directory('static', 'index.html')


@app.route('/api/attention')
def get_attention():
    errors = []

    issues_q = f"SELECT number, title, state, created_at, user_login FROM github.issues WHERE owner = '{GITHUB_USER}' AND repo = '{GITHUB_REPO}' AND state = 'open' ORDER BY created_at DESC LIMIT 10"
    issues, err = run_coral(issues_q)
    if err:
        errors.append(f"Issues: {err}")
        issues = []

    prs_q = f"SELECT number, title, merged_at, user_login FROM github.pulls WHERE owner = '{GITHUB_USER}' AND repo = '{GITHUB_REPO}' AND state = 'closed' ORDER BY merged_at DESC LIMIT 5"
    prs, err = run_coral(prs_q)
    if err:
        errors.append(f"PRs: {err}")
        prs = []

    join_q = f"SELECT g.number, g.title, s.text as slack_discussion FROM github.issues g JOIN slack.messages s ON s.channel_id = '{SLACK_CHANNEL}' WHERE g.owner = '{GITHUB_USER}' AND g.repo = '{GITHUB_REPO}' AND g.state = 'open' LIMIT 10"
    cross_join, err = run_coral(join_q)
    if err:
        errors.append(f"Join: {err}")
        cross_join = []

    slack_q = f"SELECT id, text, user, username, ts FROM slack.messages WHERE channel_id = '{SLACK_CHANNEL}' ORDER BY ts DESC LIMIT 10"
    slack, err = run_coral(slack_q)
    if err:
        errors.append(f"Slack: {err}")
        slack = []

    duplicates = find_duplicates(issues or [])
    release_notes = draft_release_notes(prs)

    return jsonify({
        'issues': issues or [],
        'prs': prs or [],
        'cross_join': cross_join or [],
        'slack': slack or [],
        'duplicates': duplicates,
        'release_notes': release_notes,
        'status': 'ok',
        'warnings': errors
    })


@app.route('/api/health')
def health():
    return jsonify({'status': 'ok', 'github_user': GITHUB_USER, 'repo': GITHUB_REPO})


if __name__ == '__main__':
    port = int(os.getenv('PORT', 5000))
    app.run(debug=False, host='0.0.0.0', port=port)
