import subprocess
import json
import os
from flask import Flask, jsonify
from dotenv import load_dotenv

load_dotenv()

app = Flask(__name__, static_folder='static')

GITHUB_USER  = os.getenv('GITHUB_USERNAME', 'YOUR_USERNAME')
GITHUB_REPO  = os.getenv('GITHUB_REPO', 'YOUR_REPO')
SLACK_CHANNEL = os.getenv('SLACK_CHANNEL_ID', 'YOUR_CHANNEL_ID')


def run_coral(query):
    """Run a Coral SQL query and return parsed JSON rows."""
    try:
        result = subprocess.run(
            ['coral', 'sql', '--output', 'json', query],
            capture_output=True, text=True, timeout=30
        )
        if result.returncode != 0:
            return None, result.stderr.strip()
        output = result.stdout.strip()
        if not output:
            return [], None
        rows = json.loads(output)
        return rows, None
    except FileNotFoundError:
        return None, "Coral CLI not found. Make sure Coral is installed: winget install withcoral.coral"
    except subprocess.TimeoutExpired:
        return None, "Coral query timed out after 30s."
    except json.JSONDecodeError:
        # fallback: return raw output as a single item
        return [{"raw": result.stdout}], None


def draft_release_notes(prs):
    """Generate simple release notes from merged PRs."""
    if not prs:
        return None
    lines = ["## Release Notes\n"]
    lines.append("### What's Changed\n")
    for pr in prs:
        title = pr.get('title', 'Untitled')
        number = pr.get('number', '?')
        user = pr.get('user_login', 'unknown')
        lines.append(f"- {title} (#{number}) — @{user}")
    lines.append(f"\n_Auto-generated by Dev's First Mate · Powered by Coral_")
    return '\n'.join(lines)


@app.route('/')
def home():
    return app.send_static_file('index.html')


@app.route('/api/attention')
def get_attention():
    errors = []

    # --- Query 1: Open Issues ---
    issues_q = f"""
        SELECT number, title, state, created_at, user_login
        FROM github.issues
        WHERE owner = '{GITHUB_USER}' AND repo = '{GITHUB_REPO}'
        AND state = 'open'
        ORDER BY created_at DESC
        LIMIT 10
    """
    issues, err = run_coral(issues_q)
    if err:
        errors.append(f"Issues query: {err}")
        issues = []

    # --- Query 2: Recently Merged PRs ---
    prs_q = f"""
        SELECT number, title, merged_at, user_login
        FROM github.pulls
        WHERE owner = '{GITHUB_USER}' AND repo = '{GITHUB_REPO}'
        AND state = 'closed'
        ORDER BY merged_at DESC
        LIMIT 5
    """
    prs, err = run_coral(prs_q)
    if err:
        errors.append(f"PRs query: {err}")
        prs = []

    # --- Query 3: Cross-source JOIN (The WOW Factor) ---
    join_q = f"""
        SELECT g.number, g.title, s.text as slack_discussion
        FROM github.issues g
        JOIN slack.messages s ON s.channel_id = '{SLACK_CHANNEL}'
        WHERE g.owner = '{GITHUB_USER}' AND g.repo = '{GITHUB_REPO}'
        AND g.state = 'open'
        LIMIT 10
    """
    cross_join, err = run_coral(join_q)
    if err:
        errors.append(f"Cross-join query: {err}")
        cross_join = []

    # --- Query 4: Slack Messages ---
    slack_q = f"""
        SELECT id, text, user, username, ts
        FROM slack.messages
        WHERE channel_id = '{SLACK_CHANNEL}'
        ORDER BY ts DESC
        LIMIT 10
    """
    slack, err = run_coral(slack_q)
    if err:
        errors.append(f"Slack query: {err}")
        slack = []

    # --- Release Notes ---
    release_notes = draft_release_notes(prs)

    response = {
        'issues': issues or [],
        'prs': prs or [],
        'cross_join': cross_join or [],
        'slack': slack or [],
        'release_notes': release_notes,
        'status': 'ok'
    }

    if errors:
        response['warnings'] = errors

    return jsonify(response)


@app.route('/api/health')
def health():
    return jsonify({'status': 'ok', 'github_user': GITHUB_USER, 'repo': GITHUB_REPO})


if __name__ == '__main__':
    print("🏴‍☠️  Dev's First Mate starting...")
    print(f"   GitHub: {GITHUB_USER}/{GITHUB_REPO}")
    print(f"   Slack channel: {SLACK_CHANNEL}")
    print("   Open: http://localhost:5000")
    app.run(debug=True, port=5000)
